version: '3.4'
services:
  myapp:
    container_name: ts-node-docker-starter
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - PORT = ${PORT}
    ports:
      - 3001:${PORT}
    env_file:
      - .env
    volumes:
      - ./:/usr/local/apps/myapp/dev
      - exclude:/usr/local/apps/myapp/dev/node_modules/
volumes:
  exclude: